version: "3"
services:
  server:
    build: ./server
    ports:
      - 1521:1521
    shm_size: 1G
    networks:
      bridge:
        aliases:
          - oracle-xe-11
  client:
    build: 
      context: ./client
    volumes:
      - ../:/home
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
