FROM store/oracle/database-enterprise:12.2.0.1

#COPY . /app

#WORKDIR /app

#RUN apt install php-curl php-gd php-intl php-json php-mbstring php-xml php-zip

#RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

#RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

#RUN php composer-setup.php

#RUN php -r "unlink('composer-setup.php');"

#RUN php composer.phar require --dev behat/behat

#CMD ['vendor/bin/behat', '-V']
